programs.chromium = {
  enable = true;
  package = null;  # nixpkgsがdarwin chromiumを提供しないので
  extensions = [
    { id = "gighmmpiobklfepjocnamgkkbiglidom"; } # adBlock
    { id = "ohahllgiabjaoigichmmfljhkcfikeof"; } # AdBlocker Ultimate
    { id = "cjpalhdlnbpafiamejdnhcphjbkeiagm"; } # uBlock
    { id = "pkehgijcmpdhfbdbbnkijodmdjhbjlgp"; } # Privacy Badger
    { id = "mlomiejdfkolichcflejclcbmpeaniij"; } # Ghostery
    { id = "bkkmolkhemgaeaeggcmfbghljjjoofoh"; } # Moca theme
    { id = "dbepggeogbaibhgnhhndojpepiihcmeb"; } # vimnium
    { id = "eimadpbcbfnmbkopoojfekhnkhdbieeh"; } # Dark Reader
    { id = "mcbpblocgmgfnpjjppndjkmgjaogfceg"; } # FireShot
    { id = "aapbdbdomjkkjkaonfhkkikfgjllcleb"; } # Google Translate
    { id = "ponfpcnoihfmfllpaingbgckeeldkhle"; } # Enhancer for YouTube™
    { id = "pcjlckhhhmlefmobnnoolakplfppdchi"; } # Ad Speedup
    { id = "flnheeellpciglgpaodhkhmapeljopja"; } # Altair GraphQL Client
    { id = "lhobafahddgcelffkeicbaginigeejlf"; } # Allow CORS: Access-Control-Allow-Origin
    { id = "bcjindcccaagfpapjjmafapmmgkkhgoa"; } # JSON Formatter
    { id = "fngmhnnpilhplaeedifhccceomclgfbg"; } # EditThisCookie
    { id = "fmkadmapgofadopljbjfkapdkoienihi"; } # React Developer Tools
    { id = "lmhkpmbekcpmknklioeibfkpmmfibljd"; } # Redux DevTools
    { id = "gppongmhjkpfnbhagpmjfkannfbllamg"; } # Wappalyzer
    { id = "cpgaheeihidjmolbakklolchdplenjai"; } # Turbo Downloader for Instagram
    { id = "cgnbfcoeopaehocfdnkkjecibafichje"; } # Mass Tiktok Video Downloader
    { id = "laookkfknpbbblfpciffpaejjkokdgca"; } # Momentum
    { id = "lahhiofdgnbcgmemekkmjnpifojdaelb"; } # Vercel
  ];
};