brew "deno"
brew "git"
brew "go"
brew "node"
brew "neovim"
brew "terraform"
brew "terraformer"
brew "vim"

cask_args appdir: "/Applications"
cask "appcleaner"
cask "balenaetcher"
cask "docker"
cask "figma"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "iterm2"
cask "microsoft-teams"
cask "mullvadvpn"
cask "skitch"
cask "slack"
cask "the-unarchiver"
cask "vlc"
cask "visual-studio-code"
cask "zeplin"
cask "zoom"